name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc
      run: sudo apt-get install -y pandoc

    - name: Create dist directory
      run: mkdir -p dist

    - name: Convert Markdown to HTML
      run: |
        for file in $(find . -name "*.md"); do
          html_file="dist/${file%.md}.html"
          mkdir -p $(dirname "$html_file")
          pandoc "$file" -o "$html_file"
        done

    - name: Commit and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
        git add dist
        git commit -m "Convert Markdown to HTML"
        git push
