name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        for file in $(find . -name "*.md"); do
          html_file="${file%.md}.html"
          pandoc "$file" -o "$html_file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Convert Markdown to HTML"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
